// Mocks generated by Mockito 5.4.6 from annotations
// in easyfile/test/core/app_trash_manager_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:easyfile/core/database/app_trash_database.dart' as _i3;
import 'package:easyfile/core/settings/app_trash_settings.dart' as _i7;
import 'package:easyfile/data/models/app_trash_item.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;
import 'package:sqflite/sqflite.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeDatabase_0 extends _i1.SmartFake implements _i2.Database {
  _FakeDatabase_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AppTrashDatabase].
///
/// See the documentation for Mockito's code generation for more information.
class MockAppTrashDatabase extends _i1.Mock implements _i3.AppTrashDatabase {
  MockAppTrashDatabase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Database> get database => (super.noSuchMethod(
        Invocation.getter(#database),
        returnValue: _i4.Future<_i2.Database>.value(_FakeDatabase_0(
          this,
          Invocation.getter(#database),
        )),
      ) as _i4.Future<_i2.Database>);

  @override
  _i4.Future<void> insert(_i5.AppTrashItem? item) => (super.noSuchMethod(
        Invocation.method(
          #insert,
          [item],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> insertBatch(List<_i5.AppTrashItem>? items) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertBatch,
          [items],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> delete(String? id) => (super.noSuchMethod(
        Invocation.method(
          #delete,
          [id],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> deleteBatch(List<String>? ids) => (super.noSuchMethod(
        Invocation.method(
          #deleteBatch,
          [ids],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<_i5.AppTrashItem?> getById(String? id) => (super.noSuchMethod(
        Invocation.method(
          #getById,
          [id],
        ),
        returnValue: _i4.Future<_i5.AppTrashItem?>.value(),
      ) as _i4.Future<_i5.AppTrashItem?>);

  @override
  _i4.Future<List<_i5.AppTrashItem>> getAll() => (super.noSuchMethod(
        Invocation.method(
          #getAll,
          [],
        ),
        returnValue:
            _i4.Future<List<_i5.AppTrashItem>>.value(<_i5.AppTrashItem>[]),
      ) as _i4.Future<List<_i5.AppTrashItem>>);

  @override
  _i4.Future<List<_i5.AppTrashItem>> getExpired(int? retentionDays) =>
      (super.noSuchMethod(
        Invocation.method(
          #getExpired,
          [retentionDays],
        ),
        returnValue:
            _i4.Future<List<_i5.AppTrashItem>>.value(<_i5.AppTrashItem>[]),
      ) as _i4.Future<List<_i5.AppTrashItem>>);

  @override
  _i4.Future<List<_i5.AppTrashItem>> getExpiringSoon(int? retentionDays) =>
      (super.noSuchMethod(
        Invocation.method(
          #getExpiringSoon,
          [retentionDays],
        ),
        returnValue:
            _i4.Future<List<_i5.AppTrashItem>>.value(<_i5.AppTrashItem>[]),
      ) as _i4.Future<List<_i5.AppTrashItem>>);

  @override
  _i4.Future<int> getTotalCount() => (super.noSuchMethod(
        Invocation.method(
          #getTotalCount,
          [],
        ),
        returnValue: _i4.Future<int>.value(0),
      ) as _i4.Future<int>);

  @override
  _i4.Future<int> getTotalSize() => (super.noSuchMethod(
        Invocation.method(
          #getTotalSize,
          [],
        ),
        returnValue: _i4.Future<int>.value(0),
      ) as _i4.Future<int>);

  @override
  _i4.Future<Map<String, int>> getCountByType() => (super.noSuchMethod(
        Invocation.method(
          #getCountByType,
          [],
        ),
        returnValue: _i4.Future<Map<String, int>>.value(<String, int>{}),
      ) as _i4.Future<Map<String, int>>);

  @override
  _i4.Future<void> clear() => (super.noSuchMethod(
        Invocation.method(
          #clear,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<String> markAsDeleted(_i5.AppTrashItem? item) =>
      (super.noSuchMethod(
        Invocation.method(
          #markAsDeleted,
          [item],
        ),
        returnValue: _i4.Future<String>.value(_i6.dummyValue<String>(
          this,
          Invocation.method(
            #markAsDeleted,
            [item],
          ),
        )),
      ) as _i4.Future<String>);

  @override
  _i4.Future<List<String>> markBatchAsDeleted(List<_i5.AppTrashItem>? items) =>
      (super.noSuchMethod(
        Invocation.method(
          #markBatchAsDeleted,
          [items],
        ),
        returnValue: _i4.Future<List<String>>.value(<String>[]),
      ) as _i4.Future<List<String>>);

  @override
  _i4.Future<void> updateStatusMoved(String? id) => (super.noSuchMethod(
        Invocation.method(
          #updateStatusMoved,
          [id],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> updateStatusFailed(String? id) => (super.noSuchMethod(
        Invocation.method(
          #updateStatusFailed,
          [id],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<List<_i5.AppTrashItem>> getPendingFiles() => (super.noSuchMethod(
        Invocation.method(
          #getPendingFiles,
          [],
        ),
        returnValue:
            _i4.Future<List<_i5.AppTrashItem>>.value(<_i5.AppTrashItem>[]),
      ) as _i4.Future<List<_i5.AppTrashItem>>);

  @override
  _i4.Future<Set<String>> getDeletedFilePaths() => (super.noSuchMethod(
        Invocation.method(
          #getDeletedFilePaths,
          [],
        ),
        returnValue: _i4.Future<Set<String>>.value(<String>{}),
      ) as _i4.Future<Set<String>>);

  @override
  _i4.Future<void> removeFromTrash(String? originalPath) => (super.noSuchMethod(
        Invocation.method(
          #removeFromTrash,
          [originalPath],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> reset() => (super.noSuchMethod(
        Invocation.method(
          #reset,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}

/// A class which mocks [AppTrashSettings].
///
/// See the documentation for Mockito's code generation for more information.
class MockAppTrashSettings extends _i1.Mock implements _i7.AppTrashSettings {
  MockAppTrashSettings() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isEnabled => (super.noSuchMethod(
        Invocation.getter(#isEnabled),
        returnValue: false,
      ) as bool);

  @override
  int get retentionDays => (super.noSuchMethod(
        Invocation.getter(#retentionDays),
        returnValue: 0,
      ) as int);

  @override
  List<int> get retentionOptions => (super.noSuchMethod(
        Invocation.getter(#retentionOptions),
        returnValue: <int>[],
      ) as List<int>);

  @override
  _i4.Future<void> setEnabled(bool? value) => (super.noSuchMethod(
        Invocation.method(
          #setEnabled,
          [value],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> setRetentionDays(int? days) => (super.noSuchMethod(
        Invocation.method(
          #setRetentionDays,
          [days],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  String getRetentionDaysText() => (super.noSuchMethod(
        Invocation.method(
          #getRetentionDaysText,
          [],
        ),
        returnValue: _i6.dummyValue<String>(
          this,
          Invocation.method(
            #getRetentionDaysText,
            [],
          ),
        ),
      ) as String);

  @override
  Map<String, dynamic> getAllSettings() => (super.noSuchMethod(
        Invocation.method(
          #getAllSettings,
          [],
        ),
        returnValue: <String, dynamic>{},
      ) as Map<String, dynamic>);

  @override
  _i4.Future<void> resetToDefaults() => (super.noSuchMethod(
        Invocation.method(
          #resetToDefaults,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  Map<String, dynamic> exportSettings() => (super.noSuchMethod(
        Invocation.method(
          #exportSettings,
          [],
        ),
        returnValue: <String, dynamic>{},
      ) as Map<String, dynamic>);

  @override
  _i4.Future<void> importSettings(Map<String, dynamic>? settings) =>
      (super.noSuchMethod(
        Invocation.method(
          #importSettings,
          [settings],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}
